### ISSUE TITLE
Investigate missing thumbnails

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-media#114]

**Comment by rudresh** [comment]
@vinayvenu I looked at most of the images with missing thumbnails in gpart organisation. All of their original images are corrupt  in the S3. Sharing a few examples below:

- 0ac047af-84f6-4cfd-be99-9b7dda1e3643.jpg
- b1daf1a2-48b0-44d1-8fb0-385e0208f24a.jpg
- c8965af8-8c52-4da9-b7fc-79e0fbb296e2.jpg
- 67f0dbe5-6f75-46d0-aa3e-a5da67cbd1cc.jpg
- f14c99d4-c363-4db6-9b6c-a50556341ae7.jpg

**Comment by 1t5j0y** [comment]
Confirmed that the images mentioned above are not valid images and this is not an issue.
