### ISSUE TITLE
Integrate media-viewer application with avni-webapp

### ISSUE THREAD

**Issue by rudresh** [avniproject/avni-media#13]
Media viewer application will be an independent application. We need to provide the access point of this application from the avni-webapp.

#### Tasks
1. Deciding appropriate place on avni-webapp where link to open the media view application will be shown.
2. Only the users authenticated on avni-webapp should be able to access the media viewer application.
3. If the user is not logged in or the session has expired, the user would be redirected to the avni-webapp login page.
3.1. Upon successful login user should be redirected to the media viewer application.

**Comment by brajesh-lab** [comment]
@petmongrels 
The commits are across multiple repos:
1. [Avni-media](https://github.com/avniproject/avni-media/commit/a89d4162129f41eb387c5a3849c847e5cd9d3a80)
2. Avni-ETL with commit names starting with 943
