### ISSUE TITLE
Previously selected options are not clearing out in the "Fields" column

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-media#133]
See video below. The fields option is not getting cleared when the question is changed. 

https://github.com/avniproject/avni-media/assets/344222/bbcd9a7c-526b-4088-8526-b7ba11d77290

**Comment by Dinesh2019** [comment]
when we remove the filter from the subject type and click on the apply filter but the image displayed is according to the subject type which we have selected previously 

https://github.com/avniproject/avni-media/assets/127730126/fca3043d-ec72-4370-92cc-de5a7177f0fa

**Comment by Dinesh2019** [comment]
we have to do fix the issue for field also
