### ISSUE TITLE
Filter by media concept

### ISSUE THREAD

**Issue by hiralatecf** [avniproject/avni-media#139]
I am not able to see all the images in the rwbngos2023 organization.
Also filtering is not open for all subjects/encounters?
I want to see images in work order registration but I am not able to.
Thank you

###  Analysis
Workorder registration images are available, but filtering by the image type is missing. Because of this, you are not able to see them in the list. 

### Story
As a media viewer used, I would like to be able to filter images by the image concept name so that I can narrow down the list of images to what I want. 

eg: In RWB, I would like to get all the pre and post perspective images alone so that I can use them in a report. Currently, it shows everything for a subject, so I get all daily images when I filter by subject. This is about 60 times the number of images that I would want to see. Filtering by concepts helps me narrow it down significantly. 

### Tech notes
- API already has the concept name based search available
- Existing app shows all concepts. Filtering these by concept datatype will help narrow down to our purpose
- Visualisation already available for concepts (search based dropdown). This can be used
- Add concept name to the name of the image

**Comment by himeshr** [comment]
## 3 development issues:
 - Token is stored in localStorage and cookies are updated in avni-media for communication
 - Paths need to be env specific config
 - Proxy needs to be reconfigured to avoid cors issues

**Comment by vinayvenu** [comment]
### Testing scenarios

- Single concept
- Multiple concepts
- Multiple concepts multiselect
- Voided concepts
- Combined with subject filter
- Combined with Fields filter
- Combined with Date filter
- All filters combined together
- No image scenario

**Comment by vinayvenu** [comment]
The filter does not work. 

Request
POST /etl/media/search
{"imageConcepts":[{"name":"Image - Farmland","uuid":"fa171bc5-81b9-4842-8014-b3449f069889","dataType":"Image"}]}

Response
http 400

**Comment by hiralatecf** [comment]
Hi Vinay, I am still not able to see the images after filtering the required destination.
Also, cannot see Registrations in Encounter type under work order subject.
Please look into this before closing this ticket.
Thank you.
With Gratitude,
Hiralchandra Maru | Asst. Manager  - Sustainable Rural Development
ATECF

________________________________

**Comment by himeshr** [comment]
Hi @hiralatecf, 
Would like to provide clarification on the card status.
The code changes for this issue will be deployed to prod server (app.avniproject.org) next week, as part of 4.0 release.
The Github cards get closed automatically on QA Complete, the fix is currently available for validation only in pre-release server.

We'll send out a notification mail to you about completion of 4.0 release, after which you may test the fix in Prod.

Kind regards,
    Himesh R
