### ISSUE TITLE
Unable to no filter on Subject and its "Registration" form

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-media#140]
**Describe the bug**
In Media-viewer application, RWB org user is reporting that he is not able to see all the images in the rwbngos2023 organization.
Specifically, they want to see images in Subject("work order") "Registration" form.

**To Reproduce**
1. Login as an RWB org admin user 
2. Go to 'Media Viewer' app in Avni-webapp
3. There is no option to filter on Subject("work order") and its "Registration" form.

**Expected behavior**
User has the ability to apply "SubjectType" and "Registration" form filters.

**Screenshots**
<img width="1840" alt="Screenshot 2023-07-14 at 9 35 02 AM" src="https://github.com/avniproject/avni-media/assets/72493481/2a0ea21e-183e-49ac-a705-5de6c62cd95d">

**Additional context**
This feature is applicable only for organisations which have "HasAnalyticsDB" enabled for them after which ETL has been run atleast once.

**Comment by vinayvenu** [comment]
@himeshr it looks like the images are present, but there are a lot of daily recordings, because of which we are not able to see these images easily. Related to #139 . Closing. Reopen if you think this analysis is wrong.

**Comment by himeshr** [comment]
On further debug, i did find the images corresponding to "WorkOrder" subjectType in the MediaViewer app, but as explained by you, there is no way to filter out images corresponding to a specific Concept.. 
We would need that capability to filter out relevant images. Marking this as duplicate of https://github.com/avniproject/avni-media/issues/139.
