### ISSUE TITLE
Cannot see photos upload using the application

### ISSUE THREAD

**Issue by shivangi** [avniproject/avni-media#145]
**Describe the bug**
While testing the Avni digitialization application I uploaded 2 photos today (28th july). I logged on to media viewer using the web portal:-
https://app.avniproject.org/avni-media?orgID=356&username=shivangi@gvamp_uat
but was unable to see these photos

**To Reproduce**
1. Go to https://app.avniproject.org/avni-media?orgID=356&username=shivangi@gvamp_uat
2. The photo link which was sent to salesforce were:-
https://app.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prod-user-media/gvamp_uat/9e0ca391-f457-46f0-97d7-187733b8fadb.jpg ; https://app.avniproject.org/web/media?url=https://s3.ap-south-1.amazonaws.com/prod-user-media/gvamp_uat/5a893fed-052b-40b5-9283-b998b99dbccc.jpg

These were viewable when clicked but could not see them on media viewer.

**Comment by vinayvenu** [comment]
The ETL works once an hour and moves all image data from the OLTP database into an analytics schema, which makes it easier to query and search. Once you upload, you might have to wait upto an hour before images are seen in the media viewer. Please see screenshot of the image that you had uploaded. 

I will add a notice on the app to this effect. 

![Image](https://github.com/avniproject/avni-media/assets/344222/01ed82ac-f121-419a-976d-c73cb357e8bb)
