### ISSUE TITLE
Filtering of Fields is not working properly

### ISSUE THREAD

**Issue by shivangi** [avniproject/avni-media#147]
Filtering by field (after choosing a subject) is not working

1. selected subject as "Activity"
2. Selected field as "Activity Category"
3. Selected value as "Cleaning" and applied filter. But the photographs did not refresh according to this filter

Tried also with field as "Tola/Mohalla" and gave a text field for it. For that too nothing changed when "Apply Filter" was pressed.

**Comment by vinayvenu** [comment]
Please check now.
