### ISSUE TITLE
Voided values are being shown in the filter criteria

### ISSUE THREAD

**Issue by shivangi** [avniproject/avni-media#148]
The filter criteria is showing voided values

for eg:
for Subject- Activity, Field - Measure Type, I can see Numbers  that are voided.

These voided values should not be visible to the users.

**Comment by vinayvenu** [comment]
Ensure that voided items are removed from the Fields as well as media type name filter.

**Comment by petmongrels** [comment]
this is the commit - 
https://github.com/avniproject/avni-media/commit/dbe3dba4a290f0fd0000f0842c6c57e193e3fa74

**Comment by AchalaBelokar** [comment]
tested on media test org.
1. created a sub type which is having the prog prog encounter .. I deleted 1st encounter after that program and void the subject type. this is not reflected in media viewer 
2. after thisI deleted the porg enc it is also not showing in the filter.
