### ISSUE TITLE
prerelease-generate-thumbnails-bulk Lambda doesnot run correctly in prerelease

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-media#151]
**Describe the bug**
prerelease-generate-thumbnails-bulk Lambda doesnot run correctly.

**To Reproduce**
https://ap-south-1.console.aws.amazon.com/lambda/home?region=ap-south-1#/functions/prerelease-generate-thumbnails-bulk?tab=code
1. Go to 'AWS Lambda console' in browser 
2. Navigate to 'prerelease-generate-thumbnails-bulk' function
3. Click on 'Test' tab
4. Invoke Test by clicking on top-right corner

**Expected behavior**
prerelease-generate-thumbnails-bulk Lambda should run successfully.

**Comment by vinayvenu** [comment]
we don't need to run this anymore as we've had a production release already, and lambdas are useless because of the time it will take (the original run took about 2 days). Closing
