### ISSUE TITLE
Force browsing to <avni_base_url>/avni-media opens the media viewer even if Analytics permissions are absent

### ISSUE THREAD

**Issue by ashusvnath** [avniproject/avni-media#153]

**Comment by vinayvenu** [comment]
@ashusvnath I believe you still won't get data even if you navigate into it. Can you confirm?

**Comment by ashusvnath** [comment]
@vinayvenu : That is correct. The search query returns a 400 series error for non-admin users (URL: https://<int_host>/etl/media/search?page=0&size=10).

**Comment by vinayvenu** [comment]
okay then.. closing this card :)
