### ISSUE TITLE
Issues with media viewer download

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-media#159]
There are multiple issues with media viewer in prod - https://drive.google.com/file/d/17-zkoHnwBPV58z2zF6cciOWX8cqn_XB8/view?usp=drive_link

5.0 of ETL and media viewer were deployed to prod.
1. Not all images selected are downloaded. - should download all images as expected

### Out of scope: will make it part of different card
1. When selecing a image all images of same names getting selected
2. No of images selected showing wrongly

Env: prod, org: RWB NITI Aayog 2022

**Comment by ashusvnath** [comment]
Noticed issues during testing on pre-release:
1. downloaded media item extension is always `.jpg`
2. image count not updated properly. It is always 0 or 1.
