### ISSUE TITLE
Naming/description of zip files

### ISSUE THREAD

**Issue by rudresh** [avniproject/avni-media#16]
Add an option to the media viewer page to put description when the user selects and downloads images. Use these description to name the zip file.

**Comment by brajesh-lab** [comment]
After deploying on staging, the server was not started, so the new code changes were not reflected.
We have restarted the server and these values are getting saved now.
As there is no code change involved, I am moving it to QA ready bucket.

**Comment by Dinesh2019** [comment]
As discussed with Rudresh we only having the description in the available download page. We are not using those description for naming Zip file when we are downloading it.
