### ISSUE TITLE
There are no concepts found for any Subject Types for Goonj

### ISSUE THREAD

**Issue by shivangi** [avniproject/avni-media#166]
For Goonj organisation i cannot find any concepts for any selected Subject Types.

This used to be there earlier.
<img width="1440" alt="Screenshot 2023-10-13 at 4 08 35 PM" src="https://github.com/avniproject/avni-media/assets/439038/1b167c92-71fd-4945-aae6-a293a2c8b2ee">

**Comment by vinayvenu** [comment]
@shivangi can you please verify once again? This looks fine when I checked, could be a one-time problem when the call to get the fields failed?

**Comment by shivangi** [comment]
@vinayvenu yes i can see them now. But not all (Name of Distribution and Activity are not seen). I have raised another issue for that. So can close this one.
