### ISSUE TITLE
Search by subject name

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-media#171]
https://avni.freshdesk.com/a/tickets/3473

It will be useful to look at all media that belongs to a specific subject (search by name only). Say when a user wants to check how a water body has improved over time

### AC:
- Add a text box like in the image below before other fields appear. 
<img width="897" alt="Screenshot 2024-04-05 at 12 45 39 PM" src="https://github.com/avniproject/avni-media/assets/10369963/ba8db602-5399-4959-9f7c-595c649cbc03">

- Matching criteria for displaying of media of subjects:(similar to DEA Name search)
    - If a part(delimitor is space) of entered text match(case insensitive) with first name of subject or
    - If a part(delimitor is space) of entered text match(case insensitive) with middle name of subject or
    - If a part(delimitor is space) of entered text match(case insensitive) with last name of subject or
- If the name entered matches(based on above matching criteria) with multiple subjects, display the media of all subjects
- The application of the Name filter need to be applied concurrently(AND) with other selected filters, if any.
- Note the release number assigned. Make sure to commit in the respective branch.

### Technical details:
- [DEA reference for search functionality](https://github.com/avniproject/avni-server/blob/dd44231098f82ce7610515accc693f543d87c2eb/avni-server-api/src/main/java/org/avni/server/dao/search/BaseSubjectSearchQueryBuilder.java#L161)
- Currently media table doesn't have ```middle name``` column. This need to be introduced.

**Comment by mahalakshme** [comment]
@vinayvenu should this be done as part of 6.1.0 considering I ve prioritised supporting RQG in DEA for 7.1.0.

**Comment by vinayvenu** [comment]
@mahalakshme did you mean 6.1.0?

**Comment by mahalakshme** [comment]
@vinayvenu sorry, I meant 7.1.0

**Comment by vinayvenu** [comment]
@mahalakshme The original reason we wanted to pick this up is because DEA is not working for everyone yet and this was required urgently. 

Also, we provide the ability to search by everything except name. Might as well add it. subject first and last names are already part of the media table, so we intended to do this, but did not complete it.

**Comment by mahalakshme** [comment]
@vinayvenu is this still relevant considering DEA display will now work with 9.0 release?

**Comment by vinayvenu** [comment]
@mahalakshme based on my understanding, this is useful irrespective of whether DEA comes in. When you know specific subject names, you have an easy way of showing all images related to it. For example, you can get all the images of a water body taken over time in a single view.

**Comment by mahalakshme** [comment]
@arjunk to check and get back if this usecase will fit within Media Viewer objective

**Comment by mahalakshme** [comment]
@vinayvenu I am convinced now. thanks for the reply.

**Comment by AchalaBelokar** [comment]
- [ ] Alignment of box should be similar to the other box , need to check the spacing between the boxes , Size of text is change in the subject name text box.
- [ ]

**Comment by 1t5j0y** [comment]
Matching criteria requirement discussed in standup and changed to match case insensitive, space delimited, 'and' of tokens similar to avniproject/avni-etl#96
