### ISSUE TITLE
In media viewer application, add the top navbar similar to avni-webapp

### ISSUE THREAD

**Issue by rudresh** [avniproject/avni-media#36]
Make the media viewer application UI, top nav bar, similar to avni-webapp. Avni-webapp doesn't have Avni logo on it. 

### Task
- Add the blue top navbar
- Write application name `Avni Media Viewer` instead of Avni Logo
- Add Home button

**Comment by brajesh-lab** [comment]
This card is covered in #38. Closing this one.
