### ISSUE TITLE
Download button on Image and carousel

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-media#37]

**Comment by Dinesh2019** [comment]
Download icon and control arrow button are overlapped so we unable to download the image instead it is moving to next image
env: staging
org: media test
Step to reproduce:
login to avni webapp
click on media viewer
click on the image
image will be popup or open in small window
in the right corner you can see the download  option 
click on it 
Expected : image should be downloaded
Actual : moving to next image
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/1f151586-8cca-406a-a9a8-a111d996c1da)
