### ISSUE TITLE
Location filters that are empty can be hidden

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-media#62]
On the Image Viewer listing page user should be able to filter image. Image can be filtered on the following parameters:

- Imagine a location filter on an organisation that has State, District and Taluka. District and Taluka filters are shown by default without any value in the dropdown. It will be better to not show these as the number of levels can be quite high. 
- Address is not getting filtered
If I select panjab as state them in district only punjab district should be shown

**Comment by brajesh-lab** [comment]
@petmongrels the commit is [here](https://github.com/avniproject/avni-media/commit/3cf2f64656570c15125205e3fc468adda1522c7e). 

While giving the commit message I referred to the wrong card number. Please use the above link for review.

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-06-05 at 9.43.07 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/cb7c1db3-2033-4e15-92c4-6cd45368f129)

- [ ] after selecting the location  I found this error

**Comment by brajesh-lab** [comment]
@AchalaBelokar @vinayvenu 
I have tried to figure out the issue and have found that the API  is returning null values for all the next-level [URLs](https://staging.avniproject.org/locations/search/find?parentId=203586&page=0&size=1000&sort=id,DESC&typeId=883)

**Comment by brajesh-lab** [comment]
@AchalaBelokar @vinayvenu I've fixed it. Please test.

**Comment by AchalaBelokar** [comment]
- [ ] need to discus with vinay

**Comment by AchalaBelokar** [comment]
- [ ] When I selected the particular location filter only that location picture should be shown .. after clicking the next button it will show me all picture

**Comment by AchalaBelokar** [comment]
- [ ] When I selected the particular location filter only that location picture should be shown .. after clicking the next button it will show me all picture
