### ISSUE TITLE
Images are shown on the encounter type dropdown so some encounter are getting behind the image 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-media#64]
Images are shown on the encounter type dropdown so some encounter are getting behind the image 
same applies for

- [ ]  subject type
- [ ]  Program

[Uploading... Screenshot 2023-05-26 at 9.01.57 AM.png]

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-05-26 at 9.01.57 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/0047473f-b7c5-4bc6-8a3b-c4a9ac4c744a)

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-05-26 at 9.01.57 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/0047473f-b7c5-4bc6-8a3b-c4a9ac4c744a)

**Comment by AchalaBelokar** [comment]
Steps to reproduce
Select any location 
click on subject type the dropdown list not showing properly         
![Screenshot 2023-06-06 at 7.25.50 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/d1df0825-ea78-4b63-b0cb-bb002b45ee2e)

**Comment by AchalaBelokar** [comment]
- [ ] ![Screenshot 2023-06-12 at 1.49.24 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/8ad5c0e3-43c2-40be-84d5-78278c4ab234)  alignment of concept filter needs to be proper

**Comment by rudresh** [comment]
Fixed the issue. Moving it to QA Ready.

**Comment by AchalaBelokar** [comment]
- [ ] All picture are in broken state in the image viewer 
- [ ]

**Comment by rudresh** [comment]
@AchalaBelokar The AWS S3 Access Key was modified because of which the malformed presigned URLs were generated. The access key was reverted and now the images are appearing fine. Please re-test it.

**Comment by brajesh-lab** [comment]
@AchalaBelokar @vinayvenu 
I have tried to figure out the issue and have found that the API  is returning null values for all the next-level [URLs](https://staging.avniproject.org/locations/search/find?parentId=203586&page=0&size=1000&sort=id,DESC&typeId=883)
