### ISSUE TITLE
Home icon should be same in the Image Viewer 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-media#66]
According to the app Every web page having the same home Icon.. But image viewer there is different  icon.. need to change  that icon
![Screenshot 2023-05-26 at 9.53.09 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/67d5b2e5-4683-48b7-abbd-20ed5d2a5478)

**Comment by AchalaBelokar** [comment]
- [ ] The tab should contain all information 
![Screenshot 2023-06-05 at 3.27.05 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/2aa67b04-4aa5-44ce-a7f1-f454aff3adea)

**Comment by rudresh** [comment]
@AchalaBelokar We have made the changes to the Home Icon. 

I suggest that we track adding additional options to the tab bar in a new issue and target it to the next release. As media viewer is a different application all together, adding these functionality will need more integration with anvi systems and can be time consuming. Moreover, it was not part of the initial scope.
