### ISSUE TITLE
Media Viewer app is showing for every orgnisation.

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-media#73]
Media Viewer app is showing for every organisation .. It should be show where we want.
for this we need to create flag type thing.
which we can on or off

Only the users authenticated on avni-webapp should be able to access the media viewer application.

**Comment by vinayvenu** [comment]
@AchalaBelokar is there a reason we need to be able to turn off Media Viewer for organisations?

**Comment by AchalaBelokar** [comment]
- @vinayvenu Not specific reason.. suppose some org don’t want that feature It will help for that..

**Comment by vinayvenu** [comment]
Closing this card as not relevant at this time.
