### ISSUE TITLE
Upgrade the home icon in Media Viewer screen 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-media#97]
- [ ] Upgrade the home icon in Media Viewer screen 
Current screen contain only home button ..
But we need to add Organisation Name ,User Name, Home button and logout option

![Screenshot 2023-06-14 at 8.43.09 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/3d79daba-a205-458d-8527-bf9ceb9c655e)![Screenshot 2023-06-14 at 8.42.47 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/9f290bd7-d4db-4d44-affd-6b0617a24544)

**Comment by petmongrels** [comment]
We will have to discuss this.
The implementation of logout, change password is all in web app. We will have to copy all that code from there to avni-media - but probably we should be modularising such common code and then adding this functionality to media viewer.

**Comment by petmongrels** [comment]
We can show username but we have to get it from token and then support keycloak and cognito. or make server call - which is the right way I think.

**Comment by petmongrels** [comment]
not do be done now. moving to done.
